framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - router_context
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - router_context
            query.bus: ~
        transports:
            sync: 'sync://'
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        routing:
            Cqs\Command\Command: sync
            Cqs\Query\Query: sync
